apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: kratos-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$2
   
spec:
  rules:
    - http:
        paths:
          - path: /()(.*)
            pathType: Prefix
            backend:
              service:
                name: kratos-ui
                port:
                  number: 80
          - path: /()(consent.*)
            pathType: Prefix
            backend:
              service:
                name: consent-ui
                port:
                  number: 80
          - path: /kratos(/|$)(.*)
            pathType: Prefix
            backend:
              service:
                name: kratos-service
                port:
                  number: 80
          - path: /hydra(/|$)(.*)
            pathType: Prefix
            backend:
              service:
                name: hydra-service
                port:
                  number: 80
          # for testing only
          - path: /hydra(/|$)(admin/.*)
            pathType: Prefix
            backend:
              service:
                name: hydra-service
                port:
                  number: 81
          # for testing only
          - path: /mailhog(/|$)(.*)
            pathType: Prefix
            backend:
              service:
                name: mail-mock
                port:
                  number: 80