apiVersion: v1
kind: Pod
metadata:
  annotations:
    kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe convert
    kompose.version: 1.27.0 (b0ed6a2c9)
  creationTimestamp: null
  labels:
    io.kompose.service: kratos-migrate
  name: kratos-migrate
spec:
  containers:
    - args:
        - -c
        - /etc/config/kratos/kratos.yml
        - migrate
        - sql
        - -e
        - --yes
      env:
        - name: DSN
          value: sqlite:///var/lib/sqlite/db.sqlite?_fk=true&mode=rwc
      image: konst/kratos
      name: kratos-migrate
      resources: {}
      volumeMounts:
        - mountPath: /var/lib/sqlite
          name: kratos-sqlite
        - mountPath: /etc/config/kratos
          name: kratos-migrate-claim1
  restartPolicy: OnFailure
  volumes:
    - name: kratos-sqlite
      persistentVolumeClaim:
        claimName: kratos-sqlite
    - name: kratos-migrate-claim1
      persistentVolumeClaim:
        claimName: kratos-migrate-claim1
status: {}
