apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe convert
    kompose.version: 1.27.0 (b0ed6a2c9)
  creationTimestamp: null
  labels:
    io.kompose.service: mailslurper
  name: mailslurper
spec:
  ports:
    - name: "4436"
      port: 4436
      targetPort: 4436
    - name: "4437"
      port: 4437
      targetPort: 4437
  selector:
    io.kompose.service: mailslurper
status:
  loadBalancer: {}
